name: Build

on:
  push:
    paths:
      - "**.cpp"
      - "**.cc"
      - "**.cxx"
      - "**.c"
      - "**.hpp"
      - "**.hh"
      - "**.hxx"
      - "**.h"
      - ".github/workflows/build.yml"
      - "**/xmake.lua"
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Cache XMake
        uses: actions/cache@v3
        with:
          path: |
            ~/AppData/Local/.xmake
            ./.xmake
          key: ${{ runner.os }}-xmake-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-xmake-

      - name: Update XMake Repository
        run: xmake repo -u

      - name: Get Release Version Tag
        if: github.event_name == 'release'
        run: echo "VERSION=${{ github.ref_name }}" >> $env:GITHUB_ENV

      - name: Get Previous Tag
        if: github.event_name != 'release'
        id: previoustag
        run: |
          $tag = ((git ls-remote -t --refs --sort=-v:refname -q | select -first 1) -split "/")[2]
          if ($tag -eq "" -or $tag -eq $null) {
            $tag = "v0.0.0"
          }
          echo "tag=$tag" >> $env:GITHUB_OUTPUT

      - name: Set Pseudo Version
        if: github.event_name != 'release'
        run: |
          $date = (Get-Date -Format "yyyyMMddHHmmss")
          $commit = git rev-parse --short HEAD
          $previous_tag = "${{ steps.previoustag.outputs.tag }}"
          echo "VERSION=$previous_tag-$date-$commit" >> $env:GITHUB_ENV

      - name: Build CrashLogger
        run: |
          xmake f -p windows -m release -a x64 --ccache=n -y
          xmake -w -y

      - name: Prepare Artifacts
        run: |
          mkdir artifacts
          cp build/windows/x64/release/CrashLogger.exe artifacts
          cp build/windows/x64/release/CrashLogger.pdb artifacts
          mv artifacts crashlogger-${{ env.VERSION }}-windows-amd64
          mkdir artifacts
          mv crashlogger-${{ env.VERSION }}-windows-amd64 artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: crashlogger-${{ env.VERSION }}-windows-amd64
          path: artifacts

  upload-to-release:
    name: Upload to Release
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Get Version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Compress Artifacts
        id: compress
        run: |
          mv crashlogger-${{ env.VERSION }}-windows-amd64 artifacts
          mv artifacts/crashlogger-${{ env.VERSION }}-windows-amd64 .
          zip -r crashlogger-${{ env.VERSION }}-windows-amd64.zip crashlogger-${{ env.VERSION }}-windows-amd64
          echo "ZIP_SHA256=$(sha256sum crashlogger-${{ env.VERSION }}-windows-amd64.zip | cut -d ' ' -f 1)" >> $GITHUB_ENV
          echo "EXE_SHA256=$(sha256sum crashlogger-${{ env.VERSION }}-windows-amd64/CrashLogger.exe | cut -d ' ' -f 1)" >> $GITHUB_ENV
          echo "PDB_SHA256=$(sha256sum crashlogger-${{ env.VERSION }}-windows-amd64/CrashLogger.pdb | cut -d ' ' -f 1)" >> $GITHUB_ENV
        shell: bash

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            crashlogger-${{ env.VERSION }}-windows-amd64.zip
            crashlogger-${{ env.VERSION }}-windows-amd64/CrashLogger.exe
            crashlogger-${{ env.VERSION }}-windows-amd64/CrashLogger.pdb
          body: |
            | File                                             | SHA256                |
            | :----------------------------------------------- | :-------------------- |
            | crashlogger-${{ env.VERSION }}-windows-amd64.zip | ${{ env.ZIP_SHA256 }} |
            | CrashLogger.exe                                  | ${{ env.EXE_SHA256 }} |
            | CrashLogger.pdb                                  | ${{ env.PDB_SHA256 }} |
